org: '1304508799'
app: test
stage: dev
component: nextjs
name: nextjs-4FlmvfzBT
inputs:
  region: ap-guangzhou
  runtime: Nodejs10.15
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
      - node_modules/**
  staticConf:
    cosConf:
      acl:
        permissions: public-read
      bucket: test-dev-1304508799
      sources:
        - src: .next
          targetDir: /_next
        - src: public
          targetDir: /
  apigatewayConf:
    serviceTimeout: 60
    autoCreateDns: false
    protocols:
      - http
      - https
    environment: release
  layers:
    - name: '${output:${stage}:${app}:test-layer.name}'
      version: '${output:${stage}:${app}:test-layer.version}'
